### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by rphlypo** [hugadams/scikit-spectra#176]
pip installing scikit-spectra yields

``` python
IOError: [Errno 2] No such file or directory: 'requirements.txt'
```

in line 16 of "/tmp/pip_build_xxx/scikit-spectra/setup.py"

**Comment by hugadams** [comment]
Hey, sorry for the late reply, I must have missed the notification on this.  Will get back to you soon.  Did you ever have any luck trying out the library?

**Comment by KelSolaar** [comment]
Same error here:

```python
(colour-skspec)Kali:Environments kelsolaar$ pip install scikit-spectra
Downloading/unpacking scikit-spectra
  Downloading scikit-spectra-0.3.2.2.tar.gz (4.3MB): 4.3MB downloaded
  Running setup.py (path:/Users/kelsolaar/Documents/Development/Environments/colour-skspec/build/scikit-spectra/setup.py) egg_info for package scikit-spectra
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/kelsolaar/Documents/Development/Environments/colour-skspec/build/scikit-spectra/setup.py", line 16, in <module>
        with open('requirements.txt', 'r') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/kelsolaar/Documents/Development/Environments/colour-skspec/build/scikit-spectra/setup.py", line 16, in <module>

    with open('requirements.txt', 'r') as f:

IOError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by rphlypo** [comment]
Nope, still not getting it working right! (sorry for this extremely late reply and thanks to @KelSolaar who reminded me of the issue)

Now giving the full error report upon calling
```bash
$ pip install scikit-spectra
```
returns:
```
Collecting scikit-spectra
  Downloading scikit-spectra-0.3.2.2.tar.gz (4.3MB)
    100% |████████████████████████████████| 4.3MB 38kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-dp2RFJ/scikit-spectra/setup.py", line 16, in <module>
        with open('requirements.txt', 'r') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dp2RFJ/scikit-spectra
```
Hope this helps in pinning the error down

**Comment by hugadams** [comment]
Thanks guys.  This is just an error in the setup.py file and can be
overcome by installing from source.  I apologize for not fixing it yet.  I
just finished my PhD, and the project should be back on track in a few
weeks.  Sorry for the delays.  There are a few major issues to flush out
(mostly due to updated versions of pandas that includes many private API
refactors).  Once I flush them out, we'll post an up-to-date release and
this will be fixed.  I'd rather not try to fix it now if we are going to
upgrade the software anyway.  Again, sorry for the delay and thanks for
your interest in the library.

On Thu, Aug 20, 2015 at 4:10 AM, rphlypo <notifications@github.com> wrote:

> Nope, still not getting it working right! (sorry for this extremely late
> reply and thanks to @KelSolaar <https://github.com/KelSolaar> who
> reminded me of the issue)
>
> Now giving the full error report upon calling
>
> $ pip install scikit-spectra
>
> returns:
>
> Collecting scikit-spectra
>   Downloading scikit-spectra-0.3.2.2.tar.gz (4.3MB)
>     100% |████████████████████████████████| 4.3MB 38kB/s
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 20, in <module>
>       File "/tmp/pip-build-dp2RFJ/scikit-spectra/setup.py", line 16, in <module>
>         with open('requirements.txt', 'r') as f:
>     IOError: [Errno 2] No such file or directory: 'requirements.txt'
>
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dp2RFJ/scikit-spectra
>
> Hope this helps in pinning the error down
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hugadams/scikit-spectra/issues/176#issuecomment-132927321>
> .
>



-- 
Adam Hughes
Physics Ph.D Candidate
George Washington University

**Comment by KelSolaar** [comment]
> This is just an error in the setup.py file and can be overcome by installing from source.

Annoying thing with installing from source is that the repo is really really massive to download (>450 mo).

**Comment by hugadams** [comment]
Right, I understand.  The documentation (IPython notebooks) have been
bundled with the repo, and really need migrated into their own repo.  I
will try to get this fixed up in the next week then; however,
scikit-spectra will still lag behind pandas and probably matplotlib in
version until we can get the next major update together.



On Fri, Aug 21, 2015 at 3:55 PM, Thomas Mansencal <notifications@github.com>
wrote:

> This is just an error in the setup.py file and can be overcome by
> installing from source.
>
> Annoying thing with installing from source is that the repo is really
> really massive to download (>450 mo).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hugadams/scikit-spectra/issues/176#issuecomment-133544891>
> .
>



-- 
Adam Hughes
Physics Ph.D Candidate
George Washington University

**Comment by KelSolaar** [comment]
Sounds good yeah! :)

**Comment by zhuobao** [comment]
Hi, this issue persists in version 0.3.2.2. A timeline for fixing it?  Thank you very much.

**Comment by frankyjuang** [comment]
Still getting this error. Any updates? Thanks.

**Comment by bharath-g** [comment]
Still gettinmg this error. Is support for this abandoned?


      File "<string>", line 1, in <module>
      File "/tmp/pip-build-FNnKKs/scikit-spectra/setup.py", line 16, in <module>
        with open('requirements.txt', 'r') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
