### ISSUE TITLE
gwuspecd script error

### ISSUE THREAD

**Issue by hugadams** [hugadams/scikit-spectra#181]
```
Traceback (most recent call last):
  File "/home/glue/Desktop/scikit-spectra/skspec/logger.py", line 228, in _wraps
    return fcn(*args, **kwargs)
  File "/home/glue/Desktop/scikit-spectra/skspec/scripts/gwu_script/gwu_controller.py", line 791, in build_timespectra
    check_for_overlapping_time=False)
  File "/home/glue/Desktop/scikit-spectra/skspec/IO/gwu_interfaces.py", line 179, in from_spec_files
    timespec=TimeSpectra(DataFrame(dict_of_series), name=name) #Dataframe beacuse TS doesn't handle dict of series
  File "/home/glue/Desktop/scikit-spectra/skspec/core/timespectra.py", line 37, in __init__
    super(TimeSpectra, self).__init__(*dfargs, **dfkwargs)
  File "/home/glue/Desktop/scikit-spectra/skspec/core/spectra.py", line 391, in __init__
    self.varunit = varunit
  File "/home/glue/Desktop/scikit-spectra/skspec/pandas_utils/metadframe.py", line 121, in __setattr__
    super(MetaPandasObject, self).__setattr__(name, value)
  File "/home/glue/Desktop/scikit-spectra/skspec/core/spectra.py", line 853, in varunit
    self.columns = CustomIndex(self.columns, unit=unit) #self.columns.setter will validate
  File "/home/glue/Desktop/scikit-spectra/skspec/pandas_utils/metadframe.py", line 121, in __setattr__
    super(MetaPandasObject, self).__setattr__(name, value)
  File "/home/glue/Desktop/scikit-spectra/skspec/core/spectra.py", line 1286, in columns
    self._frame.columns = self._valid_columns(columns)
  File "/home/glue/Desktop/scikit-spectra/skspec/core/spectra.py", line 1244, in _valid_columns
    (type(columns), self._strict_columns))
SpecError: Invalid column type: <class 'skspec.core.abcindex.CustomIndex'>; require <class 'skspec.core.timeindex.TimeIndex'>.
```

**Comment by hugadams** [comment]
Didn't I solve this in PAME notebook actually more recently?
