### ISSUE TITLE
Spectra not importing from CSV

### ISSUE THREAD

**Issue by ProtoBird** [hugadams/scikit-spectra#185]
Just downloaded and installed skspec, and trying it out with one of my csv's and I get this error, 
`>>> spc = Spectra.from_csv('E1 Kinetics.csv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/scikit_spectra-0.3.2_1-py2.7.egg/skspec/core/spectra.py", line 1643, in from_csv
    df = read_csv(filepath_or_buffer, **_CSVKWDS)
TypeError: parser_f() got an unexpected keyword argument 'na_fvalues'`

Sometime I'm doing wrong?

**Comment by GoJian** [comment]
Have a similar error message with the build-in example.

>from skspec.data import aunps_glass

>ts = aunps_glass(style=1)
ts.plot(cbar=True);
['dti', 'd', 'h', 'm', 'us', 's', 'ms', 'intvl', 'ns']
TypeError: parser_f() got an unexpected keyword argument 'na_fvalues'

Is there perhaps something wrong with my setup?  I installed from the source as instructed from wiki.

python version:

>Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)] on win32
